# Generated by Django 4.2.7 on 2023-11-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='место выполнения')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='время выполнения')),
                ('action', models.CharField(blank=True, max_length=500, null=True, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('period', models.CharField(choices=[('каждый час', 'каждый час'), ('каждый день', 'каждый день'), ('каждую неделю', 'каждую неделю'), ('каждый месяц', 'каждый месяц')], default='каждый день', max_length=30, verbose_name='периодичность выполнения привычки')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='вознаграждение')),
                ('time_to_complete', models.PositiveIntegerField(blank=True, default=60, null=True, verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
